### ISSUE TITLE
[Reg Google Analytics] My Google Analytics Id is being used

### ISSUE THREAD

**Issue by yeshwanthvshenoy** [aniketsingh222/Portfolio#1]
@aniketsingh222 

Great website 👍🏻  ! However please remove the Google Analytics from [your index.html](https://github.com/aniketsingh222/Portfolio/blob/master/index.html#L29) as your page views and being shown in my Google Analytics which I don't want!

**Comment by aniketsingh222** [comment]
Done Sir

**Comment by yeshwanthvshenoy** [comment]
@aniketsingh222 thank you!
